apiVersion: apps/v1
kind: Deployment
metadata:
  name: tansaction
  labels:
    app: tansaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tansaction
  template:
    metadata:
      labels:
        app: tansaction
    spec:
      containers:
        - name: tansaction
          image: 907740458419.dkr.ecr.ap-northeast-2.amazonaws.com/tansaction:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5